openapi: 3.0.3
info:
  title: Blog CMS REST API
  version: '1.0.0'
  description: Endpoints for authentication, content management, menus, settings, and newsletter subscriptions.
servers:
  - url: http://127.0.0.1:8000
paths:
  /api/auth/login:
    post:
      summary: Login to retrieve Sanctum token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required: [email, password]
      responses:
        '200':
          description: Logged in successfully
        '401':
          description: Invalid credentials
  /api/auth/register:
    post:
      summary: Register new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                username:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                password_confirmation:
                  type: string
              required: [name, username, email, password, password_confirmation]
      responses:
        '201':
          description: Registration success
  /api/v1/articles:
    get:
      summary: List articles
      responses:
        '200': { description: Successful response }
    post:
      summary: Create article (auth)
      security:
        - sanctum: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Article'
      responses:
        '201': { description: Article created }
  /api/v1/articles/{id}:
    get:
      summary: Show article detail
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: Successful response }
        '404': { description: Article not found }
    put:
      summary: Update article (auth)
      security: [ { sanctum: [] } ]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Article'
      responses:
        '200': { description: Article updated }
    delete:
      summary: Delete article (auth)
      security: [ { sanctum: [] } ]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: Article deleted }
  /api/v1/categories:
    get:
      summary: List categories
      responses:
        '200': { description: Successful response }
    post:
      summary: Create category (auth)
      security: [ { sanctum: [] } ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        '201': { description: Category created }
  /api/v1/categories/{id}:
    get:
      summary: Show category
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: Successful response }
    put:
      summary: Update category (auth)
      security: [ { sanctum: [] } ]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        '200': { description: Category updated }
    delete:
      summary: Delete category (auth)
      security: [ { sanctum: [] } ]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: Category deleted }
  /api/v1/tags:
    get:
      summary: List tags
      responses:
        '200': { description: Successful response }
    post:
      summary: Create tag (auth)
      security: [ { sanctum: [] } ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tag'
      responses:
        '201': { description: Tag created }
  /api/v1/tags/{id}:
    get:
      summary: Show tag
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: Successful response }
    put:
      summary: Update tag (auth)
      security: [ { sanctum: [] } ]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tag'
      responses:
        '200': { description: Tag updated }
    delete:
      summary: Delete tag (auth)
      security: [ { sanctum: [] } ]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: Tag deleted }
  /api/v1/comments:
    get:
      summary: List comments
      responses:
        '200': { description: Successful response }
    post:
      summary: Create comment (auth)
      security: [ { sanctum: [] } ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        '201': { description: Comment created }
  /api/v1/comments/{id}:
    get:
      summary: Show comment
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: Successful response }
    put:
      summary: Update comment (auth)
      security: [ { sanctum: [] } ]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        '200': { description: Comment updated }
    delete:
      summary: Delete comment (auth)
      security: [ { sanctum: [] } ]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: Comment deleted }
  /api/v1/pages:
    get:
      summary: List pages
      responses:
        '200': { description: Successful response }
    post:
      summary: Create page (auth)
      security: [ { sanctum: [] } ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Page'
      responses:
        '201': { description: Page created }
  /api/v1/pages/{id}:
    get:
      summary: Show page
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: Successful response }
    put:
      summary: Update page (auth)
      security: [ { sanctum: [] } ]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Page'
      responses:
        '200': { description: Page updated }
    delete:
      summary: Delete page (auth)
      security: [ { sanctum: [] } ]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: Page deleted }
  /api/v1/menus:
    get:
      summary: List menus
      responses:
        '200': { description: Successful response }
    post:
      summary: Create menu (auth)
      security: [ { sanctum: [] } ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Menu'
      responses:
        '201': { description: Menu created }
  /api/v1/menus/{id}:
    get:
      summary: Show menu
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: Successful response }
    put:
      summary: Update menu (auth)
      security: [ { sanctum: [] } ]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Menu'
      responses:
        '200': { description: Menu updated }
    delete:
      summary: Delete menu (auth)
      security: [ { sanctum: [] } ]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: Menu deleted }
  /api/v1/menu-items/{id}:
    put:
      summary: Update menu item (auth)
      security: [ { sanctum: [] } ]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MenuItem'
      responses:
        '200': { description: Menu item updated }
    delete:
      summary: Delete menu item (auth)
      security: [ { sanctum: [] } ]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: Menu item deleted }
  /api/v1/newsletter:
    get:
      summary: List newsletter subscribers
      responses:
        '200': { description: Successful response }
    post:
      summary: Subscribe email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Newsletter'
      responses:
        '201': { description: Subscription created }
  /api/v1/newsletter/{id}:
    delete:
      summary: Remove subscriber (auth)
      security: [ { sanctum: [] } ]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: Subscription removed }
  /api/v1/request-contributors:
    get:
      summary: List contributor requests
      responses:
        '200': { description: Successful response }
    post:
      summary: Create contributor request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestContributor'
      responses:
        '201': { description: Request created }
  /api/v1/request-contributors/{id}:
    get:
      summary: Show contributor request
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: Successful response }
    put:
      summary: Update contributor request (auth)
      security: [ { sanctum: [] } ]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestContributor'
      responses:
        '200': { description: Request updated }
    delete:
      summary: Delete contributor request (auth)
      security: [ { sanctum: [] } ]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: Request deleted }
  /api/v1/settings:
    get:
      summary: List web settings
      responses:
        '200': { description: Successful response }
    post:
      summary: Create setting (auth)
      security: [ { sanctum: [] } ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebSetting'
      responses:
        '201': { description: Setting created }
  /api/v1/settings/{id}:
    get:
      summary: Show setting
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: Successful response }
    put:
      summary: Update setting (auth)
      security: [ { sanctum: [] } ]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebSetting'
      responses:
        '200': { description: Setting updated }
    delete:
      summary: Delete setting (auth)
      security: [ { sanctum: [] } ]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: Setting deleted }
components:
  securitySchemes:
    sanctum:
      type: apiKey
      in: cookie
      name: XSRF-TOKEN
  schemas:
    Article:
      type: object
      properties:
        title: { type: string }
        content: { type: string }
        type: { type: string }
        category_id: { type: integer }
        user_id: { type: integer }
        slug: { type: string }
        status: { type: string, enum: [draft, published] }
        is_featured: { type: boolean }
        published_at: { type: string, format: date-time }
        tags:
          type: array
          items: { type: string }
      required: [title, content, type, category_id, status]
    Category:
      type: object
      properties:
        category: { type: string }
        slug: { type: string }
      required: [category]
    Tag:
      type: object
      properties:
        tag_name: { type: string }
        slug: { type: string }
      required: [tag_name]
    Comment:
      type: object
      properties:
        article_id: { type: integer }
        user_id: { type: integer }
        content: { type: string }
        parent_id: { type: integer, nullable: true }
      required: [article_id, content]
    Page:
      type: object
      properties:
        title: { type: string }
        description: { type: string }
        content: { type: string }
        slug: { type: string }
        isFullWidth: { type: boolean }
      required: [title, content]
    Menu:
      type: object
      properties:
        name: { type: string }
        location: { type: string }
      required: [name, location]
    MenuItem:
      type: object
      properties:
        label: { type: string }
        link: { type: string }
        parent: { type: integer, nullable: true }
        sort: { type: integer }
        class: { type: string }
        menu: { type: integer }
        depth: { type: integer }
      required: [label, link, menu]
    Newsletter:
      type: object
      properties:
        email: { type: string, format: email }
      required: [email]
    RequestContributor:
      type: object
      properties:
        name: { type: string }
        email: { type: string, format: email }
        description: { type: string }
        is_approved: { type: boolean }
      required: [name, email, description]
    WebSetting:
      type: object
      properties:
        key: { type: string }
        value: { type: string }
        type: { type: string }
      required: [key, value, type]
